import { Component, OnInit, ViewChild } from '@angular/core';
import {
    PepLayoutService,
    ObjectsDataRow,
    PepScreenSizeType,
    UIControl,
} from '@pepperi-addons/ngx-lib';
import {
    PepMenuItem,
    IPepMenuItemClickEvent,
} from '@pepperi-addons/ngx-lib/menu';
import { IPepSearchStateChangeEvent } from '@pepperi-addons/ngx-lib/search';
import {
    pepIconSystemBin,
    pepIconSystemSettings,
} from '@pepperi-addons/ngx-lib/icon';

import { PepBreadCrumbItem, IPepBreadCrumbItemClickEvent } from '@pepperi-addons/ngx-lib/bread-crumbs';

@Component({
    templateUrl: './carousel-example.component.html',
    styleUrls: ['./carousel-example.component.scss'],
})
export class CarouselExampleComponent implements OnInit {
    uiControl;
    items;

    title = 'client-side';

    PepScreenSizeType = PepScreenSizeType;
    screenSize: PepScreenSizeType;

    searchString = '';
    searchAutoCompleteValues = [];

    menuItems: Array<PepMenuItem>;
    breadCrumbsItems: Array<PepBreadCrumbItem>;

    constructor(public layoutService: PepLayoutService) {
        this.layoutService.onResize$.pipe().subscribe((size) => {
            this.screenSize = size;
        });
    }

    ngOnInit(): void {
        this.loadlist();
        this.loadBreadCrumbsItems();
        this.menuItems = this.getMenuItems();
    }

    loadBreadCrumbsItems() {
        this.breadCrumbsItems = [];
        this.breadCrumbsItems.push({ key: '0', text: 'Home' });
        this.breadCrumbsItems.push({ key: '1', text: 'Carusel', disabled: false });
        this.breadCrumbsItems.push({ key: '2', text: 'Carusel items', disabled: true });
    }

    getMenuItems(withChildren = true, index = 0): Array<PepMenuItem> {
        let menuItems: Array<PepMenuItem>;

        index++;

        if (withChildren) {
            menuItems = [
                {
                    key: 'test1',
                    text: 'test 1',
                    iconName: pepIconSystemBin.name,
                },
                {
                    key: 'test2',
                    text: 'test 2',
                    iconName: pepIconSystemSettings.name,
                },
                { key: 'sep', type: 'splitter' },
                {
                    key: 'test3',
                    text: 'test 3',
                    iconName: pepIconSystemBin.name,
                    children: this.getMenuItems(index <= 3, index),
                },
            ];
        } else {
            menuItems = [
                { key: 'test1', text: 'test 1' },
                { key: 'test2', text: 'test 2', disabled: true },
                { key: 'sep', type: 'splitter' },
                { key: 'test3', text: 'test 3' },
            ];
        }

        return menuItems;
    }

    loadlist() {
        const loadLines = true;
        const uiControl = loadLines
            ? this.getLinesUiControl()
            : this.getCardsUiControl();
        const rows = loadLines ? this.getLinesData() : this.getCardsData();

        this.uiControl = uiControl;
        this.items = rows;
    }

    private getLinesUiControl(): UIControl {
        return JSON.parse(
            `{
                "Columns": 9,
                "ControlFields": [
                    {
                        "ApiName": "Image",
                        "ColumnWidth": 10,
                        "ColumnWidthType": 0,
                        "FieldName": "Image",
                        "FieldType": 20,
                        "Layout": {
                            "Height": 4,
                            "LineNumber": 0,
                            "Width": 4,
                            "X": 0,
                            "XAlignment": 3,
                            "Y": 0,
                            "YAlignment": 3
                        },
                        "Mandatory": false,
                        "MaxFieldCharacters": 0,
                        "MaxFieldLines": 0,
                        "MaxValue": 1000000000,
                        "MinValue": -1000000000,
                        "ReadOnly": true,
                        "Title": ""
                    },
                    {
                        "ApiName": "ItemExternalID",
                        "ColumnWidth": 10,
                        "ColumnWidthType": 0,
                        "FieldName": "Item External ID",
                        "FieldType": 1,
                        "Layout": {
                            "Height": 1,
                            "LineNumber": 0,
                            "Width": 4,
                            "X": 4,
                            "XAlignment": 1,
                            "Y": 0,
                            "YAlignment": 3
                        },
                        "Mandatory": false,
                        "MaxFieldCharacters": 0,
                        "MaxFieldLines": 0,
                        "MaxValue": 1000000000,
                        "MinValue": -1000000000,
                        "ReadOnly": true,
                        "Title": ""
                    },
                    {
                        "ApiName": "ObjectMenu",
                        "ColumnWidth": 10,
                        "ColumnWidthType": 0,
                        "FieldName": "Object Menu",
                        "FieldType": 17,
                        "Layout": {
                            "Height": 1,
                            "LineNumber": 0,
                            "Width": 1,
                            "X": 8,
                            "XAlignment": 2,
                            "Y": 0,
                            "YAlignment": 3
                        },
                        "Mandatory": false,
                        "MaxFieldCharacters": 0,
                        "MaxFieldLines": 0,
                        "MaxValue": 1000000000,
                        "MinValue": -1000000000,
                        "ReadOnly": false,
                        "Title": ""
                    },
                    {
                        "ApiName": "ItemPrice",
                        "ColumnWidth": 10,
                        "ColumnWidthType": 0,
                        "FieldName": "Item Price",
                        "FieldType": 9,
                        "Layout": {
                            "Height": 1,
                            "LineNumber": 0,
                            "Width": 5,
                            "X": 4,
                            "XAlignment": 1,
                            "Y": 1,
                            "YAlignment": 3
                        },
                        "Mandatory": false,
                        "MaxFieldCharacters": 0,
                        "MaxFieldLines": 0,
                        "MaxValue": 1000000000,
                        "MinValue": -1000000000,
                        "ReadOnly": true,
                        "Title": ""
                    },
                    {
                        "ApiName": "ItemFutureAvailabilityDate",
                        "ColumnWidth": 0,
                        "ColumnWidthType": 0,
                        "FieldName": "Item Future Availability Date",
                        "FieldType": 5,
                        "Layout": {
                            "Height": 1,
                            "LineNumber": 0,
                            "Width": 5,
                            "X": 4,
                            "XAlignment": 1,
                            "Y": 2,
                            "YAlignment": 3
                        },
                        "Mandatory": false,
                        "MaxFieldCharacters": 0,
                        "MaxFieldLines": 0,
                        "MaxValue": 1000000000,
                        "MinValue": -1000000000,
                        "ReadOnly": true,
                        "Title": "Availabe"
                    },
                    {
                        "ApiName": "ItemLongDescription",
                        "ColumnWidth": 0,
                        "ColumnWidthType": 0,
                        "FieldName": "Item Long Description",
                        "FieldType": 1,
                        "Layout": {
                            "Height": 2,
                            "LineNumber": 0,
                            "Width": 5,
                            "X": 4,
                            "XAlignment": 1,
                            "Y": 3,
                            "YAlignment": 3
                        },
                        "Mandatory": false,
                        "MaxFieldCharacters": 0,
                        "MaxFieldLines": 0,
                        "MaxValue": 1000000000,
                        "MinValue": -1000000000,
                        "ReadOnly": true,
                        "Title": ""
                    },
                    {
                        "ApiName": "UnitsQuantity",
                        "ColumnWidth": 10,
                        "ColumnWidthType": 0,
                        "FieldName": "Unit Quantity",
                        "FieldType": 8,
                        "Layout": {
                            "Height": 2,
                            "LineNumber": 0,
                            "Width": 2,
                            "X": 1,
                            "XAlignment": 3,
                            "Y": 4,
                            "YAlignment": 3
                        },
                        "Mandatory": false,
                        "MaxFieldCharacters": 0,
                        "MaxFieldLines": 0,
                        "MaxValue": 1000000000,
                        "MinValue": -1000000000,
                        "ReadOnly": false,
                        "Title": ""
                    }
                ]
            }`
        );
    }

    private getLinesData(): Array<ObjectsDataRow> {
        return JSON.parse(
            `[{
                "AdditionalData": null,
                "BackgroundColor": "",
                "Fields": [
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "Image",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 27,
                        "FormattedValue": "https://cdn.pepperi.com/WrntyImages/30013037/PortfolioItems/8/55351188_1_200x200.jpg?ft=1",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "https://cdn.pepperi.com/WrntyImages/30013037/PortfolioItems/8/55351188_1.jpg?ft=1",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ItemExternalID",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 1,
                        "FormattedValue": "11107",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "11107",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ObjectMenu",
                        "BackgroundColor": "",
                        "Enabled": true,
                        "FieldType": 17,
                        "FormattedValue": "",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "",
                        "Visible": true
                    },
                    {
                        "Accessory": "$",
                        "AdditionalValue": "",
                        "ApiName": "ItemPrice",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 9,
                        "FormattedValue": "$35.95",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "35.9500",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ItemFutureAvailabilityDate",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 5,
                        "FormattedValue": "",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "1970-01-01",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ItemLongDescription",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 1,
                        "FormattedValue": "Using advanced edging technology and high-quality materials, our premium sunglasses have a luxurious feel with subtly curved lenses. Made with TR90 plastic, these square sunglasses are lightweight and flexible for superior comfort. The temple arms have rubber grips to keep them in place. This wide frame is available in the following colors: dark tortoiseshell (shown with dark gray tint), black (shown with dark gray tint and flame red mirror finish), and navy blue (shown with dark gray tint and sky blue mirror finish).",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "Using advanced edging technology and high-quality materials, our premium sunglasses have a luxurious feel with subtly curved lenses. Made with TR90 plastic, these square sunglasses are lightweight and flexible for superior comfort. The temple arms have rubber grips to keep them in place. This wide frame is available in the following colors: dark tortoiseshell (shown with dark gray tint), black (shown with dark gray tint and flame red mirror finish), and navy blue (shown with dark gray tint and sky blue mirror finish).",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "UnitsQuantity",
                        "BackgroundColor": "",
                        "Enabled": true,
                        "FieldType": 17,
                        "FormattedValue": "0",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "0.0000",
                        "Visible": true
                    }
                ],
                "IsEditable": false,
                "IsSelectableForActions": false,
                "MainAction": null,
                "Profile": null,
                "Type": 0,
                "UID": "c24392e3-8410-484f-aae7-65bb00a45dcc"
            },
            {
                "AdditionalData": null,
                "BackgroundColor": "",
                "Fields": [
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "Image",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 27,
                        "FormattedValue": "https://cdn.pepperi.com/WrntyImages/30013037/PortfolioItems/9/55351189_1_200x200.jpg?ft=1",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "https://cdn.pepperi.com/WrntyImages/30013037/PortfolioItems/9/55351189_1.jpg?ft=1",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ItemExternalID",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 1,
                        "FormattedValue": "11109",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "11109",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ObjectMenu",
                        "BackgroundColor": "",
                        "Enabled": true,
                        "FieldType": 17,
                        "FormattedValue": "",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "",
                        "Visible": true
                    },
                    {
                        "Accessory": "$",
                        "AdditionalValue": "",
                        "ApiName": "ItemPrice",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 9,
                        "FormattedValue": "$35.95",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "35.9500",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ItemFutureAvailabilityDate",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 5,
                        "FormattedValue": "",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "1970-01-01",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ItemLongDescription",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 1,
                        "FormattedValue": "Make a statement with these ultra-modern aviator sunglasses. The wide frame has a shiny gold metal frame front with an angular brow bar. The temple arms are made with matte black TR90 flexible plastic for a comfortable wear. Sunglasses are shown with dark gray tint with rose gold mirror finish.",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "Make a statement with these ultra-modern aviator sunglasses. The wide frame has a shiny gold metal frame front with an angular brow bar. The temple arms are made with matte black TR90 flexible plastic for a comfortable wear. Sunglasses are shown with dark gray tint with rose gold mirror finish.",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "UnitsQuantity",
                        "BackgroundColor": "",
                        "Enabled": true,
                        "FieldType": 17,
                        "FormattedValue": "0",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 1869881459,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "0.0000",
                        "Visible": true
                    }
                ],
                "IsEditable": false,
                "IsSelectableForActions": false,
                "MainAction": null,
                "Profile": null,
                "Type": 0,
                "UID": "111db36c-1fe1-46d6-969f-7e9ba19fb98b"
            },
            {
                "AdditionalData": null,
                "BackgroundColor": "",
                "Fields": [
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "Image",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 27,
                        "FormattedValue": "https://cdn.pepperi.com/WrntyImages/30013037/PortfolioItems/0/55351190_1_200x200.jpg?ft=1",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "https://cdn.pepperi.com/WrntyImages/30013037/PortfolioItems/0/55351190_1.jpg?ft=1",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ItemExternalID",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 1,
                        "FormattedValue": "11152",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "11152",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ObjectMenu",
                        "BackgroundColor": "",
                        "Enabled": true,
                        "FieldType": 17,
                        "FormattedValue": "",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "",
                        "Visible": true
                    },
                    {
                        "Accessory": "$",
                        "AdditionalValue": "",
                        "ApiName": "ItemPrice",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 9,
                        "FormattedValue": "$35.95",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "35.9500",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ItemFutureAvailabilityDate",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 5,
                        "FormattedValue": "",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "1970-01-01",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ItemLongDescription",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 1,
                        "FormattedValue": "Make a statement with these ultra-modern aviator sunglasses. The wide frame has a shiny gold metal frame front with an angular brow bar. The temple arms are made with matte black TR90 flexible plastic for a comfortable wear. Sunglasses are shown with dark gray tint with rose gold mirror finish.",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 1869881459,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "Make a statement with these ultra-modern aviator sunglasses. The wide frame has a shiny gold metal frame front with an angular brow bar. The temple arms are made with matte black TR90 flexible plastic for a comfortable wear. Sunglasses are shown with dark gray tint with rose gold mirror finish.",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "UnitsQuantity",
                        "BackgroundColor": "",
                        "Enabled": true,
                        "FieldType": 17,
                        "FormattedValue": "0",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "0.0000",
                        "Visible": true
                    }
                ],
                "IsEditable": false,
                "IsSelectableForActions": false,
                "MainAction": null,
                "Profile": null,
                "Type": 0,
                "UID": "941e160d-1a0d-41f0-9f33-100ecbc1adca"
            },
            {
                "AdditionalData": null,
                "BackgroundColor": "",
                "Fields": [
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "Image",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 27,
                        "FormattedValue": "https://cdn.pepperi.com/WrntyImages/30013037/PortfolioItems/1/55351191_1_200x200.jpg?ft=1",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "https://cdn.pepperi.com/WrntyImages/30013037/PortfolioItems/1/55351191_1.jpg?ft=1",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ItemExternalID",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 1,
                        "FormattedValue": "11158",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "11158",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ObjectMenu",
                        "BackgroundColor": "",
                        "Enabled": true,
                        "FieldType": 17,
                        "FormattedValue": "",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "",
                        "Visible": true
                    },
                    {
                        "Accessory": "$",
                        "AdditionalValue": "",
                        "ApiName": "ItemPrice",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 9,
                        "FormattedValue": "$35.95",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "35.9500",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ItemFutureAvailabilityDate",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 5,
                        "FormattedValue": "",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "1970-01-01",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ItemLongDescription",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 1,
                        "FormattedValue": "Using advanced edging technology and high-quality materials, our premium sunglasses have a luxurious feel with subtly curved lenses. Made with TR90 plastic, these square sunglasses are lightweight and flexible for superior comfort. The temple arms have rubber grips to keep them in place. This wide frame is available in the following colors: dark tortoiseshell (shown with dark gray tint), black (shown with dark gray tint and flame red mirror finish), and navy blue (shown with dark gray tint and sky blue mirror finish).",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "Using advanced edging technology and high-quality materials, our premium sunglasses have a luxurious feel with subtly curved lenses. Made with TR90 plastic, these square sunglasses are lightweight and flexible for superior comfort. The temple arms have rubber grips to keep them in place. This wide frame is available in the following colors: dark tortoiseshell (shown with dark gray tint), black (shown with dark gray tint and flame red mirror finish), and navy blue (shown with dark gray tint and sky blue mirror finish).",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "UnitsQuantity",
                        "BackgroundColor": "",
                        "Enabled": true,
                        "FieldType": 17,
                        "FormattedValue": "0",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "0.0000",
                        "Visible": true
                    }
                ],
                "IsEditable": false,
                "IsSelectableForActions": false,
                "MainAction": null,
                "Profile": null,
                "Type": 0,
                "UID": "3d274499-2c5a-4b9a-a03f-a5f88104689b"
            },
            {
                "AdditionalData": null,
                "BackgroundColor": "",
                "Fields": [
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "Image",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 27,
                        "FormattedValue": "https://cdn.pepperi.com/WrntyImages/30013037/PortfolioItems/2/55351192_1_200x200.jpg?ft=1",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "https://cdn.pepperi.com/WrntyImages/30013037/PortfolioItems/2/55351192_1.jpg?ft=1",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ItemExternalID",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 1,
                        "FormattedValue": "11161",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "11161",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ObjectMenu",
                        "BackgroundColor": "",
                        "Enabled": true,
                        "FieldType": 17,
                        "FormattedValue": "",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "",
                        "Visible": true
                    },
                    {
                        "Accessory": "$",
                        "AdditionalValue": "",
                        "ApiName": "ItemPrice",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 9,
                        "FormattedValue": "$35.95",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 1869881459,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "35.9500",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ItemFutureAvailabilityDate",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 5,
                        "FormattedValue": "",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "1970-01-01",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ItemLongDescription",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 1,
                        "FormattedValue": "Make a statement with these ultra-modern aviator sunglasses. The wide frame has a shiny gold metal frame front with an angular brow bar. The temple arms are made with matte black TR90 flexible plastic for a comfortable wear. Sunglasses are shown with dark gray tint with rose gold mirror finish.",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 1869881459,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "Make a statement with these ultra-modern aviator sunglasses. The wide frame has a shiny gold metal frame front with an angular brow bar. The temple arms are made with matte black TR90 flexible plastic for a comfortable wear. Sunglasses are shown with dark gray tint with rose gold mirror finish.",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "UnitsQuantity",
                        "BackgroundColor": "",
                        "Enabled": true,
                        "FieldType": 17,
                        "FormattedValue": "0",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 1869881459,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "0.0000",
                        "Visible": true
                    }
                ],
                "IsEditable": false,
                "IsSelectableForActions": false,
                "MainAction": null,
                "Profile": null,
                "Type": 0,
                "UID": "74820a2c-f92d-468b-a440-ae92edc01fab"
            },
            {
                "AdditionalData": null,
                "BackgroundColor": "",
                "Fields": [
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "Image",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 27,
                        "FormattedValue": "https://cdn.pepperi.com/WrntyImages/30013037/PortfolioItems/3/55351193_1_200x200.jpg?ft=1",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 1869881459,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "https://cdn.pepperi.com/WrntyImages/30013037/PortfolioItems/3/55351193_1.jpg?ft=1",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ItemExternalID",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 1,
                        "FormattedValue": "11162",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "11162",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ObjectMenu",
                        "BackgroundColor": "",
                        "Enabled": true,
                        "FieldType": 17,
                        "FormattedValue": "",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 1869881459,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "",
                        "Visible": true
                    },
                    {
                        "Accessory": "$",
                        "AdditionalValue": "",
                        "ApiName": "ItemPrice",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 9,
                        "FormattedValue": "$35.95",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 1869881459,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "35.9500",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ItemFutureAvailabilityDate",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 5,
                        "FormattedValue": "",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "1970-01-01",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ItemLongDescription",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 1,
                        "FormattedValue": "Using advanced edging technology and high-quality materials, our premium sunglasses have a luxurious feel with subtly curved lenses. Lightweight and flexible carbon fiber temple arms give these wide aviators a modern and sporty profile. The gray metal frame front has a brushed finish. Sunglasses shown with gradient gray tint.",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "Using advanced edging technology and high-quality materials, our premium sunglasses have a luxurious feel with subtly curved lenses. Lightweight and flexible carbon fiber temple arms give these wide aviators a modern and sporty profile. The gray metal frame front has a brushed finish. Sunglasses shown with gradient gray tint.",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "UnitsQuantity",
                        "BackgroundColor": "",
                        "Enabled": true,
                        "FieldType": 17,
                        "FormattedValue": "0",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "0.0000",
                        "Visible": true
                    }
                ],
                "IsEditable": false,
                "IsSelectableForActions": false,
                "MainAction": null,
                "Profile": null,
                "Type": 0,
                "UID": "f883a5e8-95a6-48a5-b211-f9f0ed1b6f70"
            },
            {
                "AdditionalData": null,
                "BackgroundColor": "",
                "Fields": [
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "Image",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 27,
                        "FormattedValue": "https://cdn.pepperi.com/WrntyImages/30013037/PortfolioItems/7/55351437_1_200x200.jpg?ft=1",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "https://cdn.pepperi.com/WrntyImages/30013037/PortfolioItems/7/55351437_1.jpg?ft=1",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ItemExternalID",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 1,
                        "FormattedValue": "11163",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "11163",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ObjectMenu",
                        "BackgroundColor": "",
                        "Enabled": true,
                        "FieldType": 17,
                        "FormattedValue": "",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 1869881459,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "",
                        "Visible": true
                    },
                    {
                        "Accessory": "$",
                        "AdditionalValue": "",
                        "ApiName": "ItemPrice",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 9,
                        "FormattedValue": "$35.95",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "35.9500",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ItemFutureAvailabilityDate",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 5,
                        "FormattedValue": "",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 1869881459,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "1970-01-01",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ItemLongDescription",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 1,
                        "FormattedValue": "Using advanced edging technology and high-quality materials, our premium sunglasses have a luxurious feel with subtly curved lenses. Made with TR90 plastic, these square sunglasses are lightweight and flexible for superior comfort. The temple arms have rubber grips to keep them in place. This wide frame is available in the following colors: dark tortoiseshell (shown with dark gray tint), black (shown with dark gray tint and flame red mirror finish), and navy blue (shown with dark gray tint and sky blue mirror finish).",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "Using advanced edging technology and high-quality materials, our premium sunglasses have a luxurious feel with subtly curved lenses. Made with TR90 plastic, these square sunglasses are lightweight and flexible for superior comfort. The temple arms have rubber grips to keep them in place. This wide frame is available in the following colors: dark tortoiseshell (shown with dark gray tint), black (shown with dark gray tint and flame red mirror finish), and navy blue (shown with dark gray tint and sky blue mirror finish).",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "UnitsQuantity",
                        "BackgroundColor": "",
                        "Enabled": true,
                        "FieldType": 17,
                        "FormattedValue": "0",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "0.0000",
                        "Visible": true
                    }
                ],
                "IsEditable": false,
                "IsSelectableForActions": false,
                "MainAction": null,
                "Profile": null,
                "Type": 0,
                "UID": "3eef19ee-d791-4708-82ff-137b3a18d0fc"
            },
            {
                "AdditionalData": null,
                "BackgroundColor": "",
                "Fields": [
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "Image",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 27,
                        "FormattedValue": "https://cdn.pepperi.com/WrntyImages/30013037/PortfolioItems/8/55351438_1_200x200.jpg?ft=1",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "https://cdn.pepperi.com/WrntyImages/30013037/PortfolioItems/8/55351438_1.jpg?ft=1",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ItemExternalID",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 1,
                        "FormattedValue": "11164",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 1869881459,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "11164",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ObjectMenu",
                        "BackgroundColor": "",
                        "Enabled": true,
                        "FieldType": 17,
                        "FormattedValue": "",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "",
                        "Visible": true
                    },
                    {
                        "Accessory": "$",
                        "AdditionalValue": "",
                        "ApiName": "ItemPrice",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 9,
                        "FormattedValue": "$35.95",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 1869881459,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "35.9500",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ItemFutureAvailabilityDate",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 5,
                        "FormattedValue": "",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 1869881459,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "1970-01-01",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ItemLongDescription",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 1,
                        "FormattedValue": "Using advanced edging technology and high-quality materials, our premium sunglasses have a luxurious look and feel with subtly curved lenses. These sunglasses offer a refined retro vibe, giving your look an instant update in the process. This boldly designed wide frame features glossy acetate with a shiny gold metal bridge and hinge accents. Opt for classic black (shown with dark gray tint and gold mirror finish) or tortoiseshell with matching temple arms (shown with dark gray tint).",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "Using advanced edging technology and high-quality materials, our premium sunglasses have a luxurious look and feel with subtly curved lenses. These sunglasses offer a refined retro vibe, giving your look an instant update in the process. This boldly designed wide frame features glossy acetate with a shiny gold metal bridge and hinge accents. Opt for classic black (shown with dark gray tint and gold mirror finish) or tortoiseshell with matching temple arms (shown with dark gray tint).",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "UnitsQuantity",
                        "BackgroundColor": "",
                        "Enabled": true,
                        "FieldType": 17,
                        "FormattedValue": "0",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "0.0000",
                        "Visible": true
                    }
                ],
                "IsEditable": false,
                "IsSelectableForActions": false,
                "MainAction": null,
                "Profile": null,
                "Type": 0,
                "UID": "b5d48e54-5849-4fbc-9a77-4989dfcd44c6"
            },
            {
                "AdditionalData": null,
                "BackgroundColor": "",
                "Fields": [
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "Image",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 27,
                        "FormattedValue": "https://cdn.pepperi.com/WrntyImages/30013037/PortfolioItems/4/55351194_1_200x200.jpg?ft=1",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 1869881459,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "https://cdn.pepperi.com/WrntyImages/30013037/PortfolioItems/4/55351194_1.jpg?ft=1",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ItemExternalID",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 1,
                        "FormattedValue": "11165",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "11165",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ObjectMenu",
                        "BackgroundColor": "",
                        "Enabled": true,
                        "FieldType": 17,
                        "FormattedValue": "",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "",
                        "Visible": true
                    },
                    {
                        "Accessory": "$",
                        "AdditionalValue": "",
                        "ApiName": "ItemPrice",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 9,
                        "FormattedValue": "$35.95",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 1869881459,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "35.9500",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ItemFutureAvailabilityDate",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 5,
                        "FormattedValue": "",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "1970-01-01",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ItemLongDescription",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 1,
                        "FormattedValue": "Using advanced edging technology and high-quality materials, our premium sunglasses have a luxurious feel with subtly curved lenses. Lightweight and flexible carbon fiber temple arms give these wide aviators a modern and sporty profile. The gray metal frame front has a brushed finish. Sunglasses shown with gradient gray tint.",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "Using advanced edging technology and high-quality materials, our premium sunglasses have a luxurious feel with subtly curved lenses. Lightweight and flexible carbon fiber temple arms give these wide aviators a modern and sporty profile. The gray metal frame front has a brushed finish. Sunglasses shown with gradient gray tint.",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "UnitsQuantity",
                        "BackgroundColor": "",
                        "Enabled": true,
                        "FieldType": 17,
                        "FormattedValue": "0",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "0.0000",
                        "Visible": true
                    }
                ],
                "IsEditable": false,
                "IsSelectableForActions": false,
                "MainAction": null,
                "Profile": null,
                "Type": 0,
                "UID": "40921895-134c-4c85-b093-f7b14e414f27"
            },
            {
                "AdditionalData": null,
                "BackgroundColor": "",
                "Fields": [
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "Image",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 27,
                        "FormattedValue": "https://cdn.pepperi.com/WrntyImages/30013037/PortfolioItems/5/55351195_1_200x200.jpg?ft=1",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "https://cdn.pepperi.com/WrntyImages/30013037/PortfolioItems/5/55351195_1.jpg?ft=1",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ItemExternalID",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 1,
                        "FormattedValue": "11166",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "11166",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ObjectMenu",
                        "BackgroundColor": "",
                        "Enabled": true,
                        "FieldType": 17,
                        "FormattedValue": "",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "",
                        "Visible": true
                    },
                    {
                        "Accessory": "$",
                        "AdditionalValue": "",
                        "ApiName": "ItemPrice",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 9,
                        "FormattedValue": "$35.95",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "35.9500",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ItemFutureAvailabilityDate",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 5,
                        "FormattedValue": "",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "1970-01-01",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "ItemLongDescription",
                        "BackgroundColor": "",
                        "Enabled": false,
                        "FieldType": 1,
                        "FormattedValue": "Make a statement with these ultra-modern aviator sunglasses. The wide frame has a shiny gold metal frame front with an angular brow bar. The temple arms are made with matte black TR90 flexible plastic for a comfortable wear. Sunglasses are shown with dark gray tint with rose gold mirror finish.",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "Make a statement with these ultra-modern aviator sunglasses. The wide frame has a shiny gold metal frame front with an angular brow bar. The temple arms are made with matte black TR90 flexible plastic for a comfortable wear. Sunglasses are shown with dark gray tint with rose gold mirror finish.",
                        "Visible": true
                    },
                    {
                        "Accessory": "",
                        "AdditionalValue": "",
                        "ApiName": "UnitsQuantity",
                        "BackgroundColor": "",
                        "Enabled": true,
                        "FieldType": 17,
                        "FormattedValue": "0",
                        "GroupFields": null,
                        "Highlighted": false,
                        "NotificationInfo": "",
                        "OptionalValues": [],
                        "ReferenceObjectInternalType": "",
                        "ReferenceObjectSubType": "",
                        "ReferenceObjectType": 0,
                        "TextColor": "",
                        "UiPageKey": "",
                        "Value": "0.0000",
                        "Visible": true
                    }
                ],
                "IsEditable": false,
                "IsSelectableForActions": false,
                "MainAction": null,
                "Profile": null,
                "Type": 0,
                "UID": "543b8487-764c-4d59-8fbf-97db7bdb8d3c"
            }]`
        );
    }

    private getCardsUiControl(): UIControl {
        return JSON.parse(
            `{
                "Columns": 9,
                "ControlFields": [
                    {
                        "ApiName": "Image",
                        "ColumnWidth": 10,
                        "ColumnWidthType": 0,
                        "FieldName": "Image",
                        "FieldType": 20,
                        "Layout": {
                            "Height": 4,
                            "LineNumber": 0,
                            "Width": 4,
                            "X": 0,
                            "XAlignment": 3,
                            "Y": 0,
                            "YAlignment": 3
                        },
                        "Mandatory": false,
                        "MaxFieldCharacters": 0,
                        "MaxFieldLines": 0,
                        "MaxValue": 1000000000,
                        "MinValue": -1000000000,
                        "ReadOnly": true,
                        "Title": ""
                    },
                    {
                        "ApiName": "ItemExternalID",
                        "ColumnWidth": 10,
                        "ColumnWidthType": 0,
                        "FieldName": "Item External ID",
                        "FieldType": 1,
                        "Layout": {
                            "Height": 1,
                            "LineNumber": 0,
                            "Width": 4,
                            "X": 4,
                            "XAlignment": 1,
                            "Y": 0,
                            "YAlignment": 3
                        },
                        "Mandatory": false,
                        "MaxFieldCharacters": 0,
                        "MaxFieldLines": 0,
                        "MaxValue": 1000000000,
                        "MinValue": -1000000000,
                        "ReadOnly": true,
                        "Title": ""
                    },
                    {
                        "ApiName": "ObjectMenu",
                        "ColumnWidth": 10,
                        "ColumnWidthType": 0,
                        "FieldName": "Object Menu",
                        "FieldType": 17,
                        "Layout": {
                            "Height": 1,
                            "LineNumber": 0,
                            "Width": 1,
                            "X": 8,
                            "XAlignment": 2,
                            "Y": 0,
                            "YAlignment": 3
                        },
                        "Mandatory": false,
                        "MaxFieldCharacters": 0,
                        "MaxFieldLines": 0,
                        "MaxValue": 1000000000,
                        "MinValue": -1000000000,
                        "ReadOnly": false,
                        "Title": ""
                    },
                    {
                        "ApiName": "ItemPrice",
                        "ColumnWidth": 10,
                        "ColumnWidthType": 0,
                        "FieldName": "Item Price",
                        "FieldType": 9,
                        "Layout": {
                            "Height": 1,
                            "LineNumber": 0,
                            "Width": 5,
                            "X": 4,
                            "XAlignment": 1,
                            "Y": 1,
                            "YAlignment": 3
                        },
                        "Mandatory": false,
                        "MaxFieldCharacters": 0,
                        "MaxFieldLines": 0,
                        "MaxValue": 1000000000,
                        "MinValue": -1000000000,
                        "ReadOnly": true,
                        "Title": ""
                    },
                    {
                        "ApiName": "ItemFutureAvailabilityDate",
                        "ColumnWidth": 0,
                        "ColumnWidthType": 0,
                        "FieldName": "Item Future Availability Date",
                        "FieldType": 5,
                        "Layout": {
                            "Height": 1,
                            "LineNumber": 0,
                            "Width": 5,
                            "X": 4,
                            "XAlignment": 1,
                            "Y": 2,
                            "YAlignment": 3
                        },
                        "Mandatory": false,
                        "MaxFieldCharacters": 0,
                        "MaxFieldLines": 0,
                        "MaxValue": 1000000000,
                        "MinValue": -1000000000,
                        "ReadOnly": true,
                        "Title": "Availabe"
                    },
                    {
                        "ApiName": "ItemLongDescription",
                        "ColumnWidth": 0,
                        "ColumnWidthType": 0,
                        "FieldName": "Item Long Description",
                        "FieldType": 1,
                        "Layout": {
                            "Height": 2,
                            "LineNumber": 0,
                            "Width": 5,
                            "X": 4,
                            "XAlignment": 1,
                            "Y": 3,
                            "YAlignment": 3
                        },
                        "Mandatory": false,
                        "MaxFieldCharacters": 0,
                        "MaxFieldLines": 0,
                        "MaxValue": 1000000000,
                        "MinValue": -1000000000,
                        "ReadOnly": true,
                        "Title": ""
                    },
                    {
                        "ApiName": "UnitsQuantity",
                        "ColumnWidth": 10,
                        "ColumnWidthType": 0,
                        "FieldName": "Unit Quantity",
                        "FieldType": 8,
                        "Layout": {
                            "Height": 2,
                            "LineNumber": 0,
                            "Width": 2,
                            "X": 1,
                            "XAlignment": 3,
                            "Y": 4,
                            "YAlignment": 3
                        },
                        "Mandatory": false,
                        "MaxFieldCharacters": 0,
                        "MaxFieldLines": 0,
                        "MaxValue": 1000000000,
                        "MinValue": -1000000000,
                        "ReadOnly": false,
                        "Title": ""
                    }
                ]
            }`
        );
    }

    private getCardsData(): Array<ObjectsDataRow> {
        return this.getLinesData();
    }

    onItemClicked(item: ObjectsDataRow): void {
        //
    }

    onMenuItemClicked(action: IPepMenuItemClickEvent): void {
        alert(action.source.key);
    }

    onBreadCrumbItemClick(event: IPepBreadCrumbItemClickEvent) {
        console.log(event);
    }

    menuClicked(event): void {
        alert('menu clicked');
    }

    onSearchStateChanged(searchStateChangeEvent: IPepSearchStateChangeEvent) {
        // debugger;
    }

    onSearchChanged(search: any) {
        // debugger;
    }

    onSearchAutocompleteChanged(value) {
        // debugger;
    }
}
